apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 3
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: mertcakmak2/k8s-kafka-consumer
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: kafka-service
              value: "kafka-service"