apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    app: consumer-service
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  selector:
    matchLabels:
      app: consumer-service
  replicas: 3
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: smeefie/consumerprototype:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: kafka-service
              value: "kafka-service"